# Generated by Django 6.0.6 on 2026-06-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('national_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=13)),
                ('father_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
    ]
