# Generated by Django 6.0.6 on 2026-06-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='father_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
