# Generated by Django 6.0.6 on 2026-06-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.PositiveIntegerField(default=100)),
                ('monthly_limit', models.PositiveIntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'سقف کلی',
            },
        ),
    ]
